services:
  - type: web
    name: shadowcore
    env: node
    region: singapore
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: PEPPER
        generateValue: true
      - key: ADMIN_PASSWORD
        value: Rana0986
      - key: RESEND_API_KEY
        value: re_KLNiEivw_CKWPC6uskbxrNP1n2chKVBv2
      - key: REMOVEBG_API_KEY
        value: xv5aoeuirxTNZBYS5KykZZEK
      - key: APP_URL
        sync: false
